version: '3'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gps
  gps:
    build: .
    hostname: gps-server
    ports:
      - "33333:33333"
   
    command: sh -c "/wait && /usr/local/bin/cmd"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - MYSQL_DATABASE=gps
      - MYSQL_ROOT_PASSWORD=secret
      - GPS_PORT=33333
volumes:
  data:
